# Generated by Django 5.1.5 on 2025-01-27 12:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "firstName",
                    models.CharField(
                        blank=True, db_column="first_name", max_length=255, null=True
                    ),
                ),
                (
                    "lastName",
                    models.CharField(
                        blank=True, db_column="last_name", max_length=255, null=True
                    ),
                ),
                ("dob", models.DateField(blank=True, db_column="dob", null=True)),
                (
                    "password",
                    models.CharField(
                        blank=True, db_column="password", max_length=255, null=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        db_column="email",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("isActive", models.BooleanField(blank=True, default=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True, db_column="gender", max_length=255, null=True
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        db_column="created_date", default=django.utils.timezone.now
                    ),
                ),
                (
                    "updated_date",
                    models.DateTimeField(
                        db_column="updated_date", default=django.utils.timezone.now
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
